### ISSUE TITLE
Wrap `then`

### ISSUE THREAD

**Issue by joelvh** [luizkowalski/concurrent_rails#2]
@luizkowalski have you used [`then`](http://ruby-concurrency.github.io/concurrent-ruby/master/Concurrent/Promises/Future.html#then-instance_method) with your futures? I want to "chain" the futures, but see that the wrapper class doesn't support `then` to also wrap the resulting chained future in the Rails executor.

I can test this out, but wanted to see if you have experience here already.

**Comment by luizkowalski** [comment]
No, I haven't used it. My use case didn't require something like chaining it with`then` so I didn't bother implementing it. Reading the docs, I see it applies to `Promises::Future`, not `Future`. Aren't you maybe looking for something like [add_observer](http://ruby-concurrency.github.io/concurrent-ruby/master/Concurrent/IVar.html#add_observer-instance_method) in this case?

**Comment by joelvh** [comment]
Yeah, I noticed that you aren't using the new interface based on promises after posting the question. I think a way to mimic this is to recursively call futures from within another future.

The concurrent-ruby docs seem to indicate they want people to move over to the promises interface. I haven't found much on why or whether they'll deprecate the others. But I do like promises from the javascript world.

**Comment by luizkowalski** [comment]
> The concurrent-ruby docs seem to indicate they want people to move over to the promises interface

do you have any link to it? when I was doing some research, I didn't find anything like this but I don't doubt it because the way i see it, using a factory for Futures is more...elegant maybe?

**Comment by joelvh** [comment]
@luizkowalski their README indicates the non-promise classes are deprecated: https://github.com/ruby-concurrency/concurrent-ruby#deprecated

**Comment by luizkowalski** [comment]
Interesting, I clearly missed this. Will play around with it later this week but if you have something in mind, shoot!

**Comment by luizkowalski** [comment]
@joelvh I found some time today and played a bit. I guess it is something. Check the [test class](https://github.com/luizkowalski/concurrent_rails/blob/master/test/promises_test.rb) to see how it is working

**Comment by joelvh** [comment]
Nice! That's nice and clean.

In my use of your gem I'm creating something like a view model for our admin area that has lots of queries, some of which are quite slow. I got things working to halve the load time. However I had to create some custom database connection stuff to extend the checkout timeout. It may be something worth considering for the gem.

I also wonder how to pool threads properly to avoid depleting main threads. I took the executor from the Rails AsyncAdapter to use what rails would use to not try and increase threads beyond what is intended to be allocated for rails.

Have you had issues with this?

**Comment by luizkowalski** [comment]
I have something similar here: there is an endpoint in the application and it loads three distinct entities from external services and they are REALLY slow. I parallelize with Futures and when I put on production, everything failed because I exhausted the resources (the pool was just too big) hahahaha

My solution was to do something like this:

1) Use `Concurrent::CachedThreadPool.new` as thread pool instead of default global io executor
2) immediately shutdown the pool with `pool.shutdown` after I computed the values. (right after the `ActiveSupport::Dependencies.interlock.permit_concurrent_loads` block

with this, I avoided depleting the resources.

> However I had to create some custom database connection stuff

Like what? I don't think this is needed when you wrap the code properly with the Rails Executor but I might be wrong. When I was using pure `Thread`s to the same task I was doing now, I had to manually call `clear_active_connections!` from `ActiveRecord` after joining the threads. Now that I wrapped on Rails, it is not necessary anymore.

**Comment by joelvh** [comment]
I basically duplicated `with_connection` in order to pass the `checkout_timeout` to `checkout`.

```ruby

      def with_connection(&block)
        pool = ActiveRecord::Base.connection_pool
        pool.release_connection
        conn = pool.checkout(30.seconds)
        cache = pool.instance_variable_get(:@thread_cached_conns)
        cache[Thread.current] = conn

        block.arity == 1 ? yield(conn) : yield
      ensure
        pool.release_connection
        ActiveRecord::Base.clear_active_connections!
      end
```

And the executor is this one, but I'm wondering if I can reference an existing executor already used for the async adapter.

```ruby
Concurrent::ThreadPoolExecutor.new(ActiveJob::QueueAdapters::AsyncAdapter::Scheduler::DEFAULT_EXECUTOR_OPTIONS)
```

In my case i must have so many parallel queries and in some cases lots of slow queries that maybe take more than the default 5s checkout timeout, cascading a connection issue. This custom `with_connection` seems to mostly fix it, but I do get some 5s timeouts on the main thread in the background sometimes. Really bizarre actually, seeing a connection error in the logs, but the UI renders fine.

Still quite a bit of playing around to do.

**Comment by joelvh** [comment]
Ah great! I knew there was work done in this area - thanks for the link. Yeah, i think that's exactly the thing we'll benefit from - I'll take a look.

**Comment by luizkowalski** [comment]
but if you feel like this gem can actually help with something in this direction, let me know...I really can't tell right now because I haven't dealt with things like this until now

**Comment by luizkowalski** [comment]
I will close this issue as the `Concurrent::Promises` wrapper is implemented and published

**Comment by joelvh** [comment]
Ah, great!

I'll report back if I have any other updates.
